<?php

class Update_model extends CI_Model{
	public function __construct(){
		$this->load->database();
	}
	/*Creates the update feed in the update table
	 *returns the id of the new entry in the table
	 */
	public function create_update($source,$type,$target){
		$data = array(
									'source' => $source,
									'type'	 => $type,
									'target' => $target,
									'timestamp' => date('Y-m-d H:i:s')
										
									);
		$query = $this->db->insert('updates',$data);
		$id = $this->db->insert_id();
		return $id;
	}
	
	/*Return all the updates generated by the connections
	*/
	public function get_updates($connections){
		
		$sql = "select * from updates where source IN (".$connections.") ";
		$query = $this->db->query($sql);
		return $query->result_array();
	}

	public function get_all(){
		$query = $this->db->get('updates');
		return $query->result_array();
	}

}

?>